### ISSUE TITLE
I am a beginner, and I don't know how to  use this plugin.

### ISSUE THREAD

**Issue by M4kWhite** [coletdjnz/yt-dlp-youtube-oauth2#10]
I am using 'yt-dlp' on win10.
I only know how to use the simplest video download or information extractor of 'yt-dlp'.
commands like 'yt-dlp -F video_id' or 'yt-dlp -f 299 video_id'.

I have two questions:
1.How do I invoke this plugin with 'yt-dlp' on win10?
2.Sometimes I debug the code of 'yt-dlp' to learn Python and how to retrieve information from YouTube. 
   How do I integrate this plugin into the 'yt-dlp' project?

**Comment by coletdjnz** [comment]
1. See details on installation here: https://github.com/coletdjnz/yt-dlp-youtube-oauth2#installation or https://github.com/yt-dlp/yt-dlp#installing-plugins if using binary
2. Same as above, depending on how you install it. It is automatically detected.

Apologies, I don't have capacity currently to provide general support - I recommend asking on the yt-dlp discord server if you are still stuck https://discord.gg/H5MNcFW63r

**Comment by M4kWhite** [comment]
I have now successfully run your OAuth2 authorization implementation code and performed various debugging.
Thanks for your help.
