### ISSUE TITLE
Instructions to apply oAuth globally for yt-dlp

### ISSUE THREAD

**Issue by nyanmeister** [coletdjnz/yt-dlp-youtube-oauth2#14]
I'd do this as a pull request, but I'm not too good at using Github.

If you use the netrc method, you can make a file at `~/.config/yt-dlp/config`, populated with:
`--netrc`

Now all attempts to use yt-dlp will use oAuth!

**Comment by nyanmeister** [comment]
Looking at this again, `--username oauth2 --password ""` could also be put in `~/.config/yt-dlp/config` to do the same thing.

**Comment by coletdjnz** [comment]
You can also use a .netrc file as described on the README 😉

https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#authentication-with-netrc

There are lots of different ways of automatically enabling it for yt-dlp

**Comment by nyanmeister** [comment]
It wouldn't work for me automatically in Syncplay, which I suspect to be because it's not inside the shell or terminal, unless I did the step I provided.

**Comment by coletdjnz** [comment]
I've mentioned it in the README for clarity
