### ISSUE TITLE
Something went wrong shown on google sign in

### ISSUE THREAD

**Issue by adyanth** [coletdjnz/yt-dlp-youtube-oauth2#15]
When trying to enter the code, google shows the "Something went wrong" webpage.

In a short while, the yt-dlp also disconnects:

```
youtube+oauth2] oauth2: Initializing OAuth2 Authorization Flow
[youtube+oauth2] To give yt-dlp access to your account, go to  https://www.google.com/device  and enter code  .........
ERROR: [youtube+oauth2] mjvPT3jJhLs: Unable to download JSON metadata: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) (caused by TransportError("('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"))
```

Is there a way to specify the path to the oauth.json file?

**Comment by miztizm** [comment]
What is you command line ? The --oauth-json flag should point to the correct path of the oauth.json file and check the permissions also

**Comment by coletdjnz** [comment]
Was this resolved? Looks like a connection problem or possibly youtube is killing the connection :thinking:
