### ISSUE TITLE
Automatic binding

### ISSUE THREAD

**Issue by LikeMeThis** [coletdjnz/yt-dlp-youtube-oauth2#17]
It seems that this plug-in can only be manually bound to the account for use, is there an automated method? For example, just set it to a configuration file

**Comment by amrutadotorg** [comment]
Hi, you only need to open the page and enter the code. Once done, you won’t be prompted again, so it’s a one-time operation.

**Comment by LikeMeThis** [comment]
But I need to go through a lot of procedures when I bind for the first time, if I have a large number of accounts that need to bind to different machine tools, is there a quick way

**Comment by coletdjnz** [comment]
See https://github.com/coletdjnz/yt-dlp-youtube-oauth2/issues/26. The cached token file stores your creds, if you want to rotate accounts then rotate the cache file. You can also use --cache-dir to work with this.

supporting multiple accounts is more of less out of scope of this plugin, as well as yt-dlp, and instead is the job for a wrapper around yt-dlp.

**Comment by coletdjnz** [comment]
I have proposed a method of supporting multiple accounts in the official oauth2 support PR: https://github.com/yt-dlp/yt-dlp/pull/11001

**Comment by coletdjnz** [comment]
Official support has been merged which supports multiple accounts

https://github.com/yt-dlp/yt-dlp/wiki/Extractors#logging-in-with-oauth
