### ISSUE TITLE
cant get urls after august 2024 update of yt-dlp

### ISSUE THREAD

**Issue by nunotfc** [coletdjnz/yt-dlp-youtube-oauth2#18]
hello, if i use this plugin, the urls got by yt-dlp are not playable. if i disable plugin, i can play it. vlc sometimes plays it, sometimes not. i use the BASS library in my program, that gives error 41, invalid file format
here is the log
withouth username and password:
[debug] Command-line config: ['-v', '-f', '[vcodec=avc1.42001E]/bestaudio/m4a/mp4', '-g', '-i', '-c', '--geo-bypass', '-4', '--cache-dir', 'cache', '--no-warnings', '--no-part', 'https://www.youtube.com/watch?v=QhGJ0EjW46I']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-116442-ge42a0763b7-20240728 (setts), ffprobe N-116442-ge42a0763b7-20240728
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Extractor Plugins: oauth2 (YoutubeBaseInfoExtractor), oauth2 (YoutubeClipIE), oauth2 (YoutubeConsentRedirectIE), oauth2 (YoutubeFavouritesIE), oauth2 (YoutubeIE), oauth2 (YoutubeMusicSearchURLIE), oauth2 (YoutubeNotificationsIE), oauth2 (YoutubeSearchDateIE), oauth2 (YoutubeSearchIE), oauth2 (YoutubeSearchURLIE), oauth2 (YoutubeTabBaseInfoExtractor), oauth2 (YoutubeTabIE)
[debug] Plugin directories: ['#omited#']
[debug] Loaded 1830 extractors
[youtube+oauth2] Extracting URL: https://www.youtube.com/watch?v=QhGJ0EjW46I
[youtube+oauth2] QhGJ0EjW46I: Downloading webpage
[youtube+oauth2] QhGJ0EjW46I: Downloading ios player API JSON
[youtube+oauth2] QhGJ0EjW46I: Downloading web creator player API JSON
[debug] [youtube+oauth2] Extracting signature function js_f8071a08_105
[youtube+oauth2] QhGJ0EjW46I: Downloading player f8071a08
[debug] Saving youtube-sigfuncs.js_f8071a08_105 to cache
[debug] Loading youtube-nsig.f8071a08 from cache
[debug] [youtube+oauth2] Decrypted nsig iFthiHHlnr2F5J1LULbM => zx2RybbvVSwsyw
[debug] [youtube+oauth2] Extracting signature function js_f8071a08_109
[debug] Loading youtube-sigfuncs.js_f8071a08_109 from cache
[debug] Loading youtube-nsig.f8071a08 from cache
[debug] [youtube+oauth2] Decrypted nsig zK-YxGEOLHqWpE7_dV_d => AOcXePLqmKKVOw
[youtube+oauth2] QhGJ0EjW46I: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] QhGJ0EjW46I: Downloading 1 format(s): 18
https://rr3---sn-2vgu0b5auxaxjvh-v2vd.googlevideo.com/videoplayback?expire=1723119941&ei=5WS0ZrPxBZ2Ip-oPwKuJgQ8&ip=188.83.222.106&id=o-APGxLnG3oYF4Vd82khgTPEBOxRKn1l-8Rq2w-m2ZKZai&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=C-&mm=31%2C29&mn=sn-2vgu0b5auxaxjvh-v2vd%2Csn-apn7en7e&ms=au%2Crdu&mv=m&mvi=3&pl=24&initcwndbps=1732500&bui=AXc671K6he7RkrYb7RxxDj4sUd8c5U3NcKf3JHJx77Sz6YMvsqm1SnP0dV7gV0ORJbpnyHqFcOW_dczB&spc=Mv1m9kmnd707J4SC4WiyQBEfs_pIRABDakCE457upbzA3ArSAiKi5A0&vprv=1&svpuc=1&mime=video%2Fmp4&ns=8plArTxARTD7qipVzrx1nhYQ&rqh=1&gir=yes&clen=9576692&ratebypass=yes&dur=182.137&lmt=1715327679561728&mt=1723098058&fvip=4&c=WEB_CREATOR&sefc=1&txp=5538434&n=zx2RybbvVSwsyw&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRAIgPp1FPvfBqq6wXGj-0671Om3Slw1V5S_QYlAHvXGUNokCIDcTYwpjMDmkN7Pv9Uywpt1VWfqdoVeXS6yX5nlb1-qY&sig=AJfQdSswRAIgUWlKsOFE-2cnVICy8sAL1T3S_ZuG_fSrwQ4_Czn8MS4CIB1Vdl4DwzxKEg4CVSRYWTjKcvDWoy0tLrlfuhrzpSth
log with oauth2:
[debug] Command-line config: ['-v', '--username', 'PRIVATE', '--password', 'PRIVATE', '-f', '[vcodec=avc1.42001E]/bestaudio/m4a/mp4', '-g', '-i', '-c', '--geo-bypass', '-4', '--cache-dir', 'cache', '--no-warnings', '--no-part', 'https://www.youtube.com/watch?v=QhGJ0EjW46I']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-116442-ge42a0763b7-20240728 (setts), ffprobe N-116442-ge42a0763b7-20240728
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Extractor Plugins: oauth2 (YoutubeBaseInfoExtractor), oauth2 (YoutubeClipIE), oauth2 (YoutubeConsentRedirectIE), oauth2 (YoutubeFavouritesIE), oauth2 (YoutubeIE), oauth2 (YoutubeMusicSearchURLIE), oauth2 (YoutubeNotificationsIE), oauth2 (YoutubeSearchDateIE), oauth2 (YoutubeSearchIE), oauth2 (YoutubeSearchURLIE), oauth2 (YoutubeTabBaseInfoExtractor), oauth2 (YoutubeTabIE)
[debug] Plugin directories: ['#omited#']
[debug] Loaded 1830 extractors
[debug] Loading youtube-oauth2.token_data from cache
[youtube+oauth2] Extracting URL: https://www.youtube.com/watch?v=QhGJ0EjW46I
[youtube+oauth2] QhGJ0EjW46I: Downloading webpage
[youtube+oauth2] QhGJ0EjW46I: Downloading ios player API JSON
[youtube+oauth2] QhGJ0EjW46I: Downloading web creator player API JSON
[youtube+oauth2] QhGJ0EjW46I: Downloading web creator player API JSON
[youtube+oauth2] QhGJ0EjW46I: Downloading web creator player API JSON
[youtube+oauth2] QhGJ0EjW46I: Downloading web creator player API JSON
[youtube+oauth2] QhGJ0EjW46I: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] QhGJ0EjW46I: Downloading 1 format(s): 140
https://rr3---sn-2vgu0b5auxaxjvh-v2vd.googlevideo.com/videoplayback?expire=1723120263&ei=J2a0ZrHRGrXQp-oPm62I4A4&ip=188.83.222.106&id=o-AMFW00ApHntBbaAbiaky4Jn9V2Mhv28OjQWdrMtrsrpw&itag=140&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=C-&mm=31%2C29&mn=sn-2vgu0b5auxaxjvh-v2vd%2Csn-apn7en7s&ms=au%2Crdu&mv=m&mvi=3&pcm2cms=yes&pl=24&initcwndbps=1870000&siu=1&vprv=1&svpuc=1&mime=audio%2Fmp4&rqh=1&gir=yes&clen=2948899&dur=182.137&lmt=1715322404285192&mt=1723098305&fvip=5&keepalive=yes&c=IOS&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Csiu%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgQnY2kaqjQH-rLo0prbJ0OXHA-zUF9J-dai7p8Czn13MCIQDcB0GPdNgqPyJOzTC3RY36U65-BA_yw9J4a4C7N-rVNA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRQIhAM02qRYFvUobMuFRPa1PE9_GM2xTD8yxU6inDRk6p8lFAiANUpQLjoaQeclOejRMr5Haj6ZAsqk2xKKtZMLVkvjniQ%3D%3D

**Comment by coletdjnz** [comment]
I think this is the same underlying issue as https://github.com/coletdjnz/yt-dlp-youtube-oauth2/issues/20, will be fixed by https://github.com/coletdjnz/yt-dlp-youtube-oauth2/pull/27
