### ISSUE TITLE
Weird python error

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [coletdjnz/yt-dlp-youtube-oauth2#24]
/usr/bin/python3 /NFS_PEERTUBE/ICN/storage/bin/yt-dlp -vU --ffmpeg-location /usr/local/ffmpeg-git/bin/ffmpeg --skip-download --playlist-reverse --flat-playlist --playlist-end 1024 --dump-json -f 'bestvideo[vcodec^=avc1][height=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=720]+bestaudio/bestvideo[vcodec^=avc1][height<=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best' 'https://rumble.com/user/C19legrandreveil/videos'
[debug] Command-line config: ['-vU', '--ffmpeg-location', '/usr/local/ffmpeg-git/bin/ffmpeg', '--skip-download', '--playlist-reverse', '--flat-playlist', '--playlist-end', '1024', '--dump-json', '-f', 'bestvideo[vcodec^=avc1][height=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=720]+bestaudio/bestvideo[vcodec^=avc1][height<=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best', 'https://rumble.com/user/C19legrandreveil/videos']
[debug] System config "/etc/yt-dlp.conf": ['--source-address', '2001:bc8:1203:362:ea2:6f1a:4546:451c', '-vU', '--geo-verification-proxy', 'rumble.com', '--proxy', 'node221.xxxx.com:3128', '--username', 'PRIVATE', '--password', 'PRIVATE', '--force-ipv4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (zip)
[debug] Python 3.12.4 (CPython x86_64 64bit) - Linux-6.10.4-x86_64-with-glibc2.39 (OpenSSL 3.2.2 4 Jun 2024, glibc 2.39)
[debug] exe versions: ffmpeg N-116611-g82085a3e0a (fdk,setts), ffprobe N-116611-g82085a3e0a
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.05.07, pyxattr-0.7.2, requests-2.32.3, sqlite3-3.45.1, urllib3-1.26.19, websockets-11.0.3
[debug] Proxy map: {'all': 'node221.xxx.com:3128'}
[debug] Request Handlers: urllib, requests
[debug] Extractor Plugins: oauth2 (YoutubeBaseInfoExtractor), oauth2 (YoutubeClipIE), oauth2 (YoutubeConsentRedirectIE), oauth2 (YoutubeFavouritesIE), oauth2 (YoutubeIE), oauth2 (YoutubeMusicSearchURLIE), oauth2 (YoutubeNotificationsIE), oauth2 (YoutubeSearchDateIE), oauth2 (YoutubeSearchIE), oauth2 (YoutubeSearchURLIE), oauth2 (YoutubeTabBaseInfoExtractor), oauth2 (YoutubeTabIE)
[debug] Plugin directories: ['/usr/local/lib64/python3.12/site-packages/yt_dlp_plugins', '/usr/local/lib/python3.12/site-packages/yt_dlp_plugins']
[debug] Loaded 1820 extractors 
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/NFS_PEERTUBE/ICN/storage/bin/yt-dlp/__main__.py", line 17, in <module>
  File "/NFS_PEERTUBE/ICN/storage/bin/yt-dlp/yt_dlp/__init__.py", line 1081, in main
  File "/NFS_PEERTUBE/ICN/storage/bin/yt-dlp/yt_dlp/__init__.py", line 1071, in _real_main
  File "/NFS_PEERTUBE/ICN/storage/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3607, in download
  File "/NFS_PEERTUBE/ICN/storage/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3582, in wrapper
  File "/NFS_PEERTUBE/ICN/storage/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1601, in extract_info
  File "/NFS_PEERTUBE/ICN/storage/bin/yt-dlp/yt_dlp/extractor/lazy_extractors.py", line 163, in suitable
NameError: name 'YoutubeTabIE' is not defined

is anyone know what's happening here?

**Comment by coletdjnz** [comment]
does `YoutubeTabIE` exist in `/NFS_PEERTUBE/ICN/storage/bin/yt-dlp/yt_dlp/extractor/youtube.py`? might be a broken yt-dlp installation

**Comment by ROBERT-MCDOWELL** [comment]
mmhmm, you re right, something wrong with this symlink.... thanks!

**Comment by coletdjnz** [comment]
https://github.com/coletdjnz/yt-dlp-youtube-oauth2/issues/43 was found to be a yt-dlp issue
