### ISSUE TITLE
help with integrating this with tubeup

### ISSUE THREAD

**Issue by 111100001** [coletdjnz/yt-dlp-youtube-oauth2#25]
i know this might not be in your scope of concern but the tubeup devs are not really helpful.

basically, the plugin works just fine but it doesn't work with tubeup ( https://github.com/bibanon/tubeup ) 

if you could help me with this issue id appreciate it 

https://github.com/bibanon/tubeup/discussions/330

**Comment by 111100001** [comment]
tubeup uses yt-dlp but i think it does so without loading yt-dlp config files. i think that's what's causing it to not work

**Comment by coletdjnz** [comment]
you've been blocked by youtube, not much you can do, except change ip

to enable the plugin you need a way to pass either the netrc command or username/password command to yt-dlp. you could try do this via a yt-dlp config file in a default directory assuming the program you are using has not disabled it.

otherwise cookies should work the same as oauth, I think there is a lot of misinfo being spread around it. If the program supports cookies then use cookies instead.

**Comment by altCensored** [comment]
i maintain a fork of tubeup which enables the authentication option [netrc], useful for [oath2], also available as a PyPI package:

https://github.com/altCensored/tubeupac
https://pypi.org/project/tubeupac/

**Comment by 111100001** [comment]
> i maintain a fork of tubeup which enables the authentication option [netrc], useful for [oath2], also available as a PyPI package:
> 
> https://github.com/altCensored/tubeupac https://pypi.org/project/tubeupac/

thank you very much!
i made a PR to the main tubeup adding the netrc option but i found out that oauth is no guarantee and might get the account banned.
our only hope is if yt-dlp implements seproDev:pass_po_token

**Comment by altCensored** [comment]
i have been using this plugin with tubeupac daily for the last 4 months.
before that i used tubeup with ipv4 and ipv6 proxies for more than 5 years.

during that almost 6 years:
- total videos and channels scraped from YT is 3.5 million plus.
- videos archived at the Internet Archive is 1.3 million plus.

google adjusts its authorization limiting, the latest large adjustment for me being a limiting of ipv6 block proxying, hence my move to this oath2 plugin.

when using these tools one needs to observe and adjust usage rates through yt-dlp options or outright waits/sleeps in your python script.

i am currently uing a sleep of between 2 and 5 seconds between invocations of tubeupac / yt-dlp-youtube-oauth2 with success:
  time.sleep(random.randint(2, 5))
  
if your google account is flagged for excessive oath2 use, you can always wait a day of so, adjust, and try again.

good luck and don't give up!

**Comment by 111100001** [comment]
hello im back again to ask if you have had any issues since this. my vps is still balcklisted even though i have not used it in months. youtube might have perma blocked data center ip ranges since my VPS is an Oracle Free Tier one
