### ISSUE TITLE
Unable to download JSON metadata: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by jamessu1201** [coletdjnz/yt-dlp-youtube-oauth2#28]
I use username oauth2 ,but i met this error.
this is my ytdl_options:
YTDL_OPTIONS = {
        'username':'oauth2',
        'password':'',
        'format': 'bestaudio/best',
        'extractaudio': True,
        'audioformat': 'mp3',
        'outtmpl': '%(extractor)s-%(id)s-%(title)s.%(ext)s',
        'restrictfilenames': True,
        'noplaylist': True,
        'nocheckcertificate': True,
        'ignoreerrors': False,
        'logtostderr': False,
        'quiet': True,
        'no_warnings': True,
        'default_search': 'auto',
        'source_address': '0.0.0.0',
    }
this is my error log:
2024-08-17 07:50:09 INFO     discord.voice_client Voice handshake complete. Endpoint found singapore11002.discord.media
ERROR: [youtube+oauth2] hmTyMGb8BHg: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
disconnect

**Comment by coletdjnz** [comment]
with the non-verbose log I'm assuming this is the same as https://github.com/coletdjnz/yt-dlp-youtube-oauth2/issues/20
