### ISSUE TITLE
How to used this plugin in python code?

### ISSUE THREAD

**Issue by rmaleki** [coletdjnz/yt-dlp-youtube-oauth2#29]
I want to use this plugin in my code. I couldn't find any documentation on this topic.

```
from yt_dlp import YoutubeDL

ydl_opts = {
    "quiet": True,
    "extract_flat": True,
    "force_generic_extractor": True,
    "cachedir": "/tmp",
}

with YoutubeDL(ydl_opts) as ydl:
    result = ydl.extract_info(reel_path, download=True)

```

**Comment by coletdjnz** [comment]
Install as normal, and should be able to just pass `{'username': 'oauth2', 'password': ''}` to ydl to enable

run ydl with `'verbose': True` to check that it is loaded if it is not working.
