### ISSUE TITLE
dl-plus support?

### ISSUE THREAD

**Issue by 111100001** [coletdjnz/yt-dlp-youtube-oauth2#30]
can i add this plugin into dl-plus? 

https://github.com/un-def/dl-plus

**Comment by 111100001** [comment]
i tried it but i must've done something wrong

**Comment by coletdjnz** [comment]
This plugin is designed for the official yt-dlp plugin system only... I can't provide support for other systems and can't guarantee it will work with them. You should consult with the author of dl-plus.
