### ISSUE TITLE
The plugin doesn't work with live youtube video when --live-from-start flag is used

### ISSUE THREAD

**Issue by PfAndrey** [coletdjnz/yt-dlp-youtube-oauth2#31]
I'm using yt-dlp with this oauth2 plugin on my AWS server.
And as we know Youtube recently restricted normall access from AWS and other cloud services.

For me the plugin is working well for regular Youtube videos.
But it's failed for live videos when I'm trying to capture it from the start (i.e. using --live-from-start flag).

For an example, with this command (5eFtlG93mHE - can be any live video id):

     # yt-dlp  --username oauth2 --password '' --live-from-start https://www.youtube.com/watch?v=5eFtlG93mHE 

I got such output: 

    youtube+oauth2] Extracting URL: https://www.youtube.com/watch?v=5eFtlG93mHE
    [youtube+oauth2] 5eFtlG93mHE: Downloading webpage
    [youtube+oauth2] 5eFtlG93mHE: Downloading ios player API JSON
    [youtube+oauth2] 5eFtlG93mHE: Downloading web creator player API JSON
    WARNING: [youtube+oauth2] YouTube said: ERROR - Request contains an invalid argument.
    WARNING: [youtube+oauth2] HTTP Error 400: Bad Request. Retrying (1/3)...
    [youtube+oauth2] 5eFtlG93mHE: Downloading web creator player API JSON
    WARNING: [youtube+oauth2] YouTube said: ERROR - Request contains an invalid argument.
    WARNING: [youtube+oauth2] HTTP Error 400: Bad Request. Retrying (2/3)...
    [youtube+oauth2] 5eFtlG93mHE: Downloading web creator player API JSON
    WARNING: [youtube+oauth2] YouTube said: ERROR - Request contains an invalid argument.
    WARNING: [youtube+oauth2] HTTP Error 400: Bad Request. Retrying (3/3)...
    [youtube+oauth2] 5eFtlG93mHE: Downloading web creator player API JSON
    WARNING: [youtube+oauth2] YouTube said: ERROR - Request contains an invalid argument.
    WARNING: [youtube+oauth2] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
    ERROR: [youtube+oauth2] 5eFtlG93mHE: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Without "--live-from-start" flag it works good for live videos.
Also "--live-from-start" flag works well with already published (not live videos)

Any thoughts?

**Comment by khift363** [comment]
Seconding this. Very recent issue -- been using --live-from-start with this plugin for months, and as of earlier this week it was working, but now I get the same error 100% of the time.

**Comment by coletdjnz** [comment]
same issue as https://github.com/coletdjnz/yt-dlp-youtube-oauth2/issues/20
