### ISSUE TITLE
Not able to get best format after using oauth2 

### ISSUE THREAD

**Issue by checkdev7** [coletdjnz/yt-dlp-youtube-oauth2#32]
When i'm using the oauth2 and trying to get the url for best fomart 
yt-dlp -f best -g "https://www.youtube.com/watch?v=MC4feT1VN0k" --list-formats --username oauth2 --password '' 
I'm not getting the best format. Below Image

<img width="962" alt="best-format" src="https://github.com/user-attachments/assets/e1af2de6-c526-4509-8435-428453bb12ae">

But while using the yt-dlp without oauth2 I'm getting the best format url.
yt-dlp -f best -g "https://www.youtube.com/watch?v=MC4feT1VN0k" --list-formats
I'm getting best format. Below Image
<img width="1426" alt="best" src="https://github.com/user-attachments/assets/a4caeb44-38e9-4ea0-9a20-28633f1d8f79">

**Comment by coletdjnz** [comment]
same issue as https://github.com/coletdjnz/yt-dlp-youtube-oauth2/issues/20
