### ISSUE TITLE
Cannot refresh OAuth2 Token

### ISSUE THREAD

**Issue by Zackoswald** [coletdjnz/yt-dlp-youtube-oauth2#39]
I made a wrapper to rotate the cache files, but it wont refresh tokens correctly
[youtube+oauth2] Access token expired, refreshing
[youtube+oauth2] oauth2: Refreshing OAuth2 Token
ERROR: [youtube+oauth2] _7CvH5em5og: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 737, in extract
    self.initialize()
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 643, in initialize
    self._perform_login(username, password)
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp_plugins/extractor/youtubeoauth.py", line 177, in _perform_login
    self.initialize_oauth()
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp_plugins/extractor/youtubeoauth.py", line 62, in initialize_oauth
    token_data = self.refresh_token(token_data['refresh_token'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp_plugins/extractor/youtubeoauth.py", line 91, in refresh_token
    token_response = self._download_json(
                     ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1139, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1099, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 960, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 909, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 896, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4165, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 340, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp/networking/_requests.py", line 365, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 400: Bad Request

**Comment by coletdjnz** [comment]
Can you give the output with --verbose pls

**Comment by Zackoswald** [comment]
你好，邮件我已收到！

**Comment by Zackoswald** [comment]
here is the output:
[debug] Command-line config: ['-u', 'PRIVATE', '-p', 'PRIVATE', 'https://youtube.com/watch?v=_7CvH5em5og', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.08.26.232811 from yt-dlp/yt-dlp-nightly-builds [41be32e78] (pip)
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-6.8.0-1014-aws-x86_64-with-glibc2.39 (OpenSSL 3.0.15 3 Sep 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.3, urllib3-2.2.2, websockets-13.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Extractor Plugins: oauth2 (YoutubeClipIE), oauth2 (YoutubeConsentRedirectIE), oauth2 (YoutubeFavouritesIE), oauth2 (YoutubeIE), oauth2 (YoutubeMusicSearchURLIE), oauth2 (YoutubeNotificationsIE), oauth2 (YoutubeSearchDateIE), oauth2 (YoutubeSearchIE), oauth2 (YoutubeSearchURLIE), oauth2 (YoutubeTabIE)
[debug] Plugin directories: ['/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp_plugins']
[debug] Loaded 1831 extractors
[debug] YouTube OAuth2 plugin version 2024.08.31.1
[debug] Loading youtube-oauth2.token_data from cache
[youtube+oauth2] Access token expired, refreshing
[youtube+oauth2] oauth2: Refreshing OAuth2 Token
ERROR: [youtube+oauth2] _7CvH5em5og: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 737, in extract
    self.initialize()
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 643, in initialize
    self._perform_login(username, password)
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp_plugins/extractor/youtubeoauth.py", line 177, in _perform_login
    self.initialize_oauth()
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp_plugins/extractor/youtubeoauth.py", line 62, in initialize_oauth
    token_data = self.refresh_token(token_data['refresh_token'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp_plugins/extractor/youtubeoauth.py", line 91, in refresh_token
    token_response = self._download_json(
                     ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1139, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1099, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 960, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 909, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 896, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4165, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 340, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/python3.11/lib/python3.11/site-packages/yt_dlp/networking/_requests.py", line 365, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 400: Bad Request
Thankful for your help:)

**Comment by Zackoswald** [comment]
it happends everyday and i need to bound the account manually to recover it

**Comment by coletdjnz** [comment]
Hmm, I can't reproduce.

Someone on discord got this too but they had an unofficial version installed, and reinstalling the official version worked. Though yours looks like it should be fine in this regards.

Try reinstalling perhaps (using the method as described on the README)?

**Comment by Zackoswald** [comment]
okay, i will try it and report it if it happend again

**Comment by ROBERT-MCDOWELL** [comment]
so what is the best way to refresh the oauth2 and/or keep it when server reboots?

**Comment by coletdjnz** [comment]
> so what is the best way to refresh the oauth2 and/or keep it when server reboot?
> here is an example of a verbose request with yt-dlp
> yt-dlp --verbose https://youtu.be/eT4OivMpU2Q?si=lxv_aScdcgx1NM75
> [debug] Command-line config: ['--verbose', 'https://youtu.be/eT4OivMpU2Q?si=lxv_aScdcgx1NM75']
> [debug] System config "/etc/yt-dlp.conf": ['--source-address', 'XXX', '-vU', '--geo-verification-proxy', 'rumble.com', '--proxy', 'node221.xxx.com:3128', '--username', 'PRIVATE', '--password', 'PRIVATE', '--no-cookies', '--force-ipv4']
> [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
> [debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (zip)
> [debug] Python 3.12.5 (CPython x86_64 64bit) - Linux-6.10.10-x86_64-with-glibc2.39 (OpenSSL 3.2.2 4 Jun 2024, glibc 2.39)
> [debug] exe versions: ffmpeg 5.1.6 (fdk,setts), ffprobe 5.1.6
> [debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.05.07, pyxattr-0.7.2, requests-2.32.3, sqlite3-3.45.1, urllib3-1.26.19, websockets-13.0
> [debug] Proxy map: {'all': 'node221.xxx.com:3128'}
> [debug] Request Handlers: urllib, requests, websockets
> [debug] Extractor Plugins: oauth2 (YoutubeBaseInfoExtractor), oauth2 (YoutubeClipIE), oauth2 (YoutubeConsentRedirectIE), oauth2 (YoutubeFavouritesIE), oauth2 (YoutubeIE), oauth2 (YoutubeMusicSearchURLIE), oauth2 (YoutubeNotificationsIE), oauth2 (YoutubeSearchDateIE), oauth2 (YoutubeSearchIE), oauth2 (YoutubeSearchURLIE), oauth2 (YoutubeTabBaseInfoExtractor), oauth2 (YoutubeTabIE)
> [debug] Plugin directories: ['/usr/local/lib64/python3.12/site-packages/yt_dlp_plugins', '/usr/local/lib/python3.12/site-packages/yt_dlp_plugins']
> [debug] Loaded 1830 extractors
> [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
> Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
> yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
> [debug] Loading youtube-oauth2.token_data from cache
> [youtube+oauth2] Extracting URL: https://youtu.be/eT4OivMpU2Q?si=lxv_aScdcgx1NM75
> [youtube+oauth2] eT4OivMpU2Q: Downloading webpage
> [youtube+oauth2] eT4OivMpU2Q: Downloading ios player API JSON
> [youtube+oauth2] eT4OivMpU2Q: Downloading web creator player API JSON
> WARNING: [youtube+oauth2] YouTube said: ERROR - Request contains an invalid argument.
> WARNING: [youtube+oauth2] HTTP Error 400: Bad Request. Retrying (1/3)...
> [youtube+oauth2] eT4OivMpU2Q: Downloading web creator player API JSON
> WARNING: [youtube+oauth2] YouTube said: ERROR - Request contains an invalid argument.
> WARNING: [youtube+oauth2] HTTP Error 400: Bad Request. Retrying (2/3)...
> [youtube+oauth2] eT4OivMpU2Q: Downloading web creator player API JSON
> WARNING: [youtube+oauth2] YouTube said: ERROR - Request contains an invalid argument.
> WARNING: [youtube+oauth2] HTTP Error 400: Bad Request. Retrying (3/3)...
> [youtube+oauth2] eT4OivMpU2Q: Downloading web creator player API JSON
> WARNING: [youtube+oauth2] YouTube said: ERROR - Request contains an invalid argument.
> WARNING: [youtube+oauth2] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
> [youtube+oauth2] eT4OivMpU2Q: Downloading m3u8 information
> [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
> [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
> [debug] Default format spec: bestvideo*+bestaudio/best
> [info] eT4OivMpU2Q: Downloading 1 format(s): 247+251
> [debug] Invoking http downloader on "https://rr2---sn-ixh7yn7d.googlevideo.com/videoplayback?expire=1726195199&ei=n1HjZveHI9GOv_IP1Ou6uAE&ip=95.216.71.221&id=o-ANlKCCgwliuvzIjYHscqHyG5Zg028E7502yp7rQkt89P&itag=247&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=1t&mm=31%2C26&mn=sn-ixh7yn7d%2Csn-nv47zn7y&ms=au%2Conr&mv=m&mvi=2&pl=24&initcwndbps=613750&siu=1&vprv=1&svpuc=1&mime=video%2Fwebm&rqh=1&gir=yes&clen=16011797&dur=480.840&lmt=1725472796118774&mt=1726173185&fvip=1&keepalive=yes&c=IOS&txp=5535434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Csiu%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgbuf6ZerHsWZT7HGuD1OJ9c7sY21JG7B0_xGr5tncsqECIQDknTvQ3VC1NGSg0NHKXaSm1jgzVS1MOd6V_f2JvaimGw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ABPmVW0wRQIgAntzkKVWCwH-I8_N_crqgy2fUJSVfuWUjKOJQ1WXlSMCIQCi_Ez0Q6m1eq-Cc0hRjoalgj_5zcUt4Bpvo4vlemJl2Q%3D%3D"
> [download] Destination: R.I.P. Alison Carey ✝︎ Retour sur ses témoignages de 2018 & 2020 ⧸ Culte Satanique ⧸ Mariah Carey [eT4OivMpU2Q].f247.webm
> [download] 100% of   15.27MiB in 00:00:00 at 17.25MiB/s
> [debug] Invoking http downloader on "https://rr2---sn-ixh7yn7d.googlevideo.com/videoplayback?expire=1726195199&ei=n1HjZveHI9GOv_IP1Ou6uAE&ip=95.216.71.221&id=o-ANlKCCgwliuvzIjYHscqHyG5Zg028E7502yp7rQkt89P&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=1t&mm=31%2C26&mn=sn-ixh7yn7d%2Csn-nv47zn7y&ms=au%2Conr&mv=m&mvi=2&pl=24&initcwndbps=613750&siu=1&vprv=1&svpuc=1&mime=audio%2Fwebm&rqh=1&gir=yes&clen=6411400&dur=480.861&lmt=1725467789061140&mt=1726173185&fvip=1&keepalive=yes&c=IOS&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Csiu%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgBTKb-8tuG94mleX1uXnfLdWdXq_J1O-vQW-R1w03INcCIAOqOsSzSD1sh22xBMBVifbHSTqrMYtoUQMugL0DZ1_S&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ABPmVW0wRQIgAntzkKVWCwH-I8_N_crqgy2fUJSVfuWUjKOJQ1WXlSMCIQCi_Ez0Q6m1eq-Cc0hRjoalgj_5zcUt4Bpvo4vlemJl2Q%3D%3D"
> [download] Destination: R.I.P. Alison Carey ✝︎ Retour sur ses témoignages de 2018 & 2020 ⧸ Culte Satanique ⧸ Mariah Carey [eT4OivMpU2Q].f251.webm
> [download] 100% of    6.11MiB in 00:00:00 at 29.36MiB/s
> [Merger] Merging formats into "R.I.P. Alison Carey ✝︎ Retour sur ses témoignages de 2018 & 2020 ⧸ Culte Satanique ⧸ Mariah Carey [eT4OivMpU2Q].webm"
> [debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:R.I.P. Alison Carey ✝︎ Retour sur ses témoignages de 2018 & 2020 ⧸ Culte Satanique ⧸ Mariah Carey [eT4OivMpU2Q].f247.webm' -i 'file:R.I.P. Alison Carey ✝︎ Retour sur ses témoignages de 2018 & 2020 ⧸ Culte Satanique ⧸ Mariah Carey [eT4OivMpU2Q].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:R.I.P. Alison Carey ✝︎ Retour sur ses témoignages de 2018 & 2020 ⧸ Culte Satanique ⧸ Mariah Carey [eT4OivMpU2Q].temp.webm'
> 

It is working fine for you, just that you need to update the plugin and yt-dlp (to nightly)

**Comment by ROBERT-MCDOWELL** [comment]
ok thanks! I used to use yt-dlp last git but had issues to run it since months now so I'm stuck with the last release for now.
I saw that the token is stored in /dev/shm ram file so that's why after each reboot the token disappear and I have to reactivate again on google... so maybe I just need to save the yt-dlp cache folder somewhere and copy  it agin in /dev/shm after reboot or is there a better way to save it?

**Comment by coletdjnz** [comment]
> ok thanks! I used to use yt-dlp last git but had issues to run it since months now so I'm stuck with the last release for now.
> I saw that the token is stored in /dev/shm ram file so that's why after each reboot the token disappear and I have to reactivate again on google... so maybe I just need to save the yt-dlp cache folder somewhere and copy  it agin in /dev/shm after reboot or is there a better way to save it?

The token is stored in the yt-dlp cache dir. The default is based on your system settings, however you can specify a custom dir with --cache-dir.

**Comment by ROBERT-MCDOWELL** [comment]
thanks! btw when I compile yt-dlp from git and run it I get:
[debug] Command-line config: ['--verbose', 'https://youtu.be/n8z6CsCK2_w?si=4xiRVdU-bY1_irnA']
[debug] System config "/etc/yt-dlp.conf": ['--source-address', '2605:80:7:3:7449:514:600f:3f8e', '-uV', '--no-cookies', '--ffmpeg-location', '/usr/local/ffmpeg-git/bin/ffmpeg', '--username', 'PRIVATE', '--password', 'PRIVATE', '--force-ipv4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (zip)
[debug] Python 3.12.5 (CPython x86_64 64bit) - Linux-6.10.10-x86_64-with-glibc2.39 (OpenSSL 3.2.2 4 Jun 2024, glibc 2.39)
[debug] exe versions: ffmpeg N-116987-g071c499026 (fdk,setts), ffprobe N-116987-g071c499026
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2020.06.20, pyxattr-0.7.2, sqlite3-3.45.1, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Extractor Plugins: oauth2 (YoutubeClipIE), oauth2 (YoutubeConsentRedirectIE), oauth2 (YoutubeFavouritesIE), oauth2 (YoutubeIE), oauth2 (YoutubeMusicSearchURLIE), oauth2 (YoutubeNotificationsIE), oauth2 (YoutubeSearchDateIE), oauth2 (YoutubeSearchIE), oauth2 (YoutubeSearchURLIE), oauth2 (YoutubeTabIE)
[debug] Plugin directories: ['/usr/local/lib64/python3.12/site-packages/yt_dlp_plugins', '/usr/local/lib/python3.12/site-packages/yt_dlp_plugins']
[debug] Loaded 1822 extractors
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/src/yt-dlp/./yt-dlp/__main__.py", line 17, in <module>
  File "/home/src/yt-dlp/./yt-dlp/yt_dlp/__init__.py", line 1081, in main
  File "/home/src/yt-dlp/./yt-dlp/yt_dlp/__init__.py", line 1071, in _real_main
  File "/home/src/yt-dlp/./yt-dlp/yt_dlp/YoutubeDL.py", line 3607, in download
  File "/home/src/yt-dlp/./yt-dlp/yt_dlp/YoutubeDL.py", line 3582, in wrapper
  File "/home/src/yt-dlp/./yt-dlp/yt_dlp/YoutubeDL.py", line 1601, in extract_info
  File "/home/src/yt-dlp/./yt-dlp/yt_dlp/extractor/lazy_extractors.py", line 163, in suitable
NameError: name 'YoutubeTabIE' is not defined

**Comment by coletdjnz** [comment]
> thanks! btw when I compile yt-dlp from git and run it I get: [debug] Command-line config: ['--verbose', 'https://youtu.be/n8z6CsCK2_w?si=4xiRVdU-bY1_irnA'] [debug] System config "/etc/yt-dlp.conf": ['--source-address', '2605:80:7:3:7449:514:600f:3f8e', '-uV', '--no-cookies', '--ffmpeg-location', '/usr/local/ffmpeg-git/bin/ffmpeg', '--username', 'PRIVATE', '--password', 'PRIVATE', '--force-ipv4'] [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8 [debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (zip) [debug] Python 3.12.5 (CPython x86_64 64bit) - Linux-6.10.10-x86_64-with-glibc2.39 (OpenSSL 3.2.2 4 Jun 2024, glibc 2.39) [debug] exe versions: ffmpeg N-116987-g071c499026 (fdk,setts), ffprobe N-116987-g071c499026 [debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2020.06.20, pyxattr-0.7.2, sqlite3-3.45.1, websockets-11.0.3 [debug] Proxy map: {} [debug] Request Handlers: urllib [debug] Extractor Plugins: oauth2 (YoutubeClipIE), oauth2 (YoutubeConsentRedirectIE), oauth2 (YoutubeFavouritesIE), oauth2 (YoutubeIE), oauth2 (YoutubeMusicSearchURLIE), oauth2 (YoutubeNotificationsIE), oauth2 (YoutubeSearchDateIE), oauth2 (YoutubeSearchIE), oauth2 (YoutubeSearchURLIE), oauth2 (YoutubeTabIE) [debug] Plugin directories: ['/usr/local/lib64/python3.12/site-packages/yt_dlp_plugins', '/usr/local/lib/python3.12/site-packages/yt_dlp_plugins'] [debug] Loaded 1822 extractors Traceback (most recent call last): File "", line 198, in _run_module_as_main File "", line 88, in _run_code File "/home/src/yt-dlp/./yt-dlp/**main**.py", line 17, in File "/home/src/yt-dlp/./yt-dlp/yt_dlp/**init**.py", line 1081, in main File "/home/src/yt-dlp/./yt-dlp/yt_dlp/**init**.py", line 1071, in _real_main File "/home/src/yt-dlp/./yt-dlp/yt_dlp/YoutubeDL.py", line 3607, in download File "/home/src/yt-dlp/./yt-dlp/yt_dlp/YoutubeDL.py", line 3582, in wrapper File "/home/src/yt-dlp/./yt-dlp/yt_dlp/YoutubeDL.py", line 1601, in extract_info File "/home/src/yt-dlp/./yt-dlp/yt_dlp/extractor/lazy_extractors.py", line 163, in suitable NameError: name 'YoutubeTabIE' is not defined

you might need to run `devscripts/make_lazy_extractors.py`, or remove the lazy_extractors file. this is getting offtopic for this plugin, you should go to upstream yt-dlp for help if that doesn't work

**Comment by ROBERT-MCDOWELL** [comment]
ok thanks!

**Comment by Zackoswald** [comment]
你好，邮件我已收到！
