### ISSUE TITLE
Oauth2 flow in user interface

### ISSUE THREAD

**Issue by Bruxar** [coletdjnz/yt-dlp-youtube-oauth2#42]
I'm currently running yt-dlp on a server, and I have encountered an issue with the OAuth authorization flow. When the OAuth process is initiated, the corresponding messages, including the verification URL and user code, only appear in the server's console. This setup is problematic because users do not have direct access to the server console to see these messages.

I believe it would be beneficial to show this authorization flow directly to the user through a web interface via an API response. However, I have struggled to capture and return the authorization messages to the user effectively.

I attempted to capture the console output and send it back through the API, but I haven't had any success with this approach.

Any guidance or suggestions on how to achieve this would be greatly appreciated!

**Comment by coletdjnz** [comment]
Depending on how you are running yt-dlp you should be able to capture the message. If you are still needing help, this would be better to ask over in the yt-dlp discord/matrix server. 

This plugin is now obsolete and will no longer be maintained

https://github.com/coletdjnz/yt-dlp-youtube-oauth2/commit/aabcf895c317357a052180588cddd2982fa7bd63

**Comment by ROBERT-MCDOWELL** [comment]
@coletdjnz 
first of all many thanks for this great idea of plugin that helps many of us to continue to download videos from YT (especially the ones that can be censored quickly). I read the wiki and guess that for us whom already use the plugin just need to uninstall it as the command line and config are the same right?

**Comment by coletdjnz** [comment]
> @coletdjnz 
> first of all many thanks for this great idea of plugin that helps many of us to continue to download videos from YT (especially the ones that can be censored quickly). I read the wiki and guess that for us whom already use the plugin just need to uninstall it as the command line and config are the same right?

Yes pretty much, except that the "oauth2" username is "oauth" in the official version. You'll need to log in again

**Comment by ROBERT-MCDOWELL** [comment]
ok good to know, thanks!
