### ISSUE TITLE
video unavailable issue

### ISSUE THREAD

**Issue by hliang2-sn** [coletdjnz/yt-dlp-youtube-oauth2#45]
I started parallel process to download videos. After a while, my youtube account meets the issue of 'video unavailable'. I cannot watch any videos with my account. How to solve it?

**Comment by Bruxar** [comment]
I think your ip was throttled, may trying with a proxy should work.

**Comment by amrutadotorg** [comment]
based on my experience, you account has been banned, try to use different account and do not download too much videos in one go.

**Comment by coletdjnz** [comment]
as mentioned, you account is temporary blocked by youtube for downloading too much. slow down your downloading.

I also recommend passing a PO Token to help avoid getting banned 

https://github.com/yt-dlp/yt-dlp/wiki/Extractors#po-token-guide
