### ISSUE TITLE
There is NO support in official version

### ISSUE THREAD

**Issue by Delitants** [coletdjnz/yt-dlp-youtube-oauth2#47]
I don't know what are you talking about, but even nightly builds of yt-dlp do NOT support oauth, it just ignores user and password inputs. Once I installed this plugin, it started to work. So what you wrote on the main page is false.

yt-dlp -v
[debug] Command-line config: ['-v']
[debug] Encodings: locale ISO-8859-1, fs iso8859-1, pref ISO-8859-1, out iso8859-1, error iso8859-1, screen iso8859-1
[debug] yt-dlp version nightly@2024.10.28.232846 from yt-dlp/yt-dlp-nightly-builds [f101e5d34] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-91-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.37.2, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Plugin directories: ['/usr/local/lib/python3.10/dist-packages/yt_dlp_plugins']

 /usr/local/bin/yt-dlp --username #####@gmail.com --password "#####" --proxy "socks5://#######" https://www.youtube.com/watch?v=##### -v    
[debug] Command-line config: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--proxy', 'socks5://********', 'https://www.youtube.com/watch?v=****', '-v']
[debug] Encodings: locale ISO-8859-1, fs iso8859-1, pref ISO-8859-1, out iso8859-1, error iso8859-1, screen iso8859-1
[debug] yt-dlp version nightly@2024.10.28.232846 from yt-dlp/yt-dlp-nightly-builds [f101e5d34] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-91-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.37.2, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {'all': 'socks5://#####'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Plugin directories: ['/usr/local/lib/python3.10/dist-packages/yt_dlp_plugins']
[debug] Loaded 1837 extractors
ERROR: [youtube] *******: Use  --username=oauth[+PROFILE] --password=""  to log in using oauth, or else use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. See  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#logging-in-with-oauth  for more on how to use oauth. See  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for help with cookies
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 739, in extract
    self.initialize()
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 645, in initialize
    self._perform_login(username, password)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/youtube.py", line 583, in _perform_login
    raise ExtractorError(self._youtube_login_hint, expected=True)

**Comment by coletdjnz** [comment]
> ERROR: [youtube] *******: Use --username=oauth[+PROFILE] --password="" to log in using oauth, or else use --cookies-from-browser or --cookies for the authentication. See https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp for how to manually pass cookies. See https://github.com/yt-dlp/yt-dlp/wiki/Extractors#logging-in-with-oauth for more on how to use oauth. See https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies for help with cookies

Read this message and see the linked wiki page https://github.com/yt-dlp/yt-dlp/wiki/Extractors#logging-in-with-oauth

If there is an issue open one on the yt-dlp repo

**Comment by ROBERT-MCDOWELL** [comment]
@coletdjnz I'm confused you just release a new version today, so does it update also on yt-dlp repo?

**Comment by coletdjnz** [comment]
> @coletdjnz I'm confused you just release a new version today, so does it update also on yt-dlp repo?

The new version includes a warning that the plugin is deprecated and that you should use the official oauth implementation instead.

**Comment by ROBERT-MCDOWELL** [comment]
ha! oki :D
