### ISSUE TITLE
How to work around vimeo

### ISSUE THREAD

**Issue by tjesp** [coletdjnz/yt-dlp-youtube-oauth2#5]
Hi, I have put 

`--username oauth2 --password ''`

In my config file. Now I have the problem that vimeo links errors with invalid username or password. How do I work around that?

**Comment by coletdjnz** [comment]
Unfortunately this is an issue with yt-dlp where the username/password parameters is applied globally.

You can instead use a netrc file to define username/password for youtube only:

https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#authentication-with-netrc

For youtube with oauth2:
```
machine youtube login oauth2
````

**Comment by tjesp** [comment]
Allright thanks. I kept getting an error until my .netrc looked like:

`machine youtube login oauth2 password ""`

I post it here in case anyone else get this problem.

**Comment by coletdjnz** [comment]
Odd, it works without the password my end :thinking: 

I'll add it to the readme :+1:
