### ISSUE TITLE
Got response ... instead of ...

### ISSUE THREAD

**Issue by tjesp** [coletdjnz/yt-dlp-youtube-oauth2#6]
I get the following warning recently:

WARNING: [youtube+oauth2] Skipping player responses from android clients (got player responses for video "aQvGIIdgFDM" instead of "PrhMXSzgM5Q")

I am not sure whether this means anything serious since its only a warning. I just thought I would bring it up.

I use yt-dlp nightly build.

**Comment by coletdjnz** [comment]
It's an issue in yt-dlp https://github.com/yt-dlp/yt-dlp/issues/9554

Though you can ignore it
