### ISSUE TITLE
How to change the account

### ISSUE THREAD

**Issue by mingzhang96** [coletdjnz/yt-dlp-youtube-oauth2#8]
I used an account and logged in successfully until the account was blocked.  Now I want to change the account, and I try
```
yt-dlp -vU --list-formats --username oauth2 --password 'password_from_new_account' "https://www.youtube.com/watch?v=xxxxx"
```
but it seems to be still using the old account. Could you show how to change the account?

**Comment by coletdjnz** [comment]
The access token is stored in the cache, which you clean clear from yt-dlp with `--rm-cache-dir`

**Comment by mingzhang96** [comment]
> The access token is stored in the cache, which you can clear from yt-dlp with `--rm-cache-dir`
> 
> After that it should prompt you again to log in.

`yt-dlp --rm-cache-dir` works! Thanks for your response!
