### ISSUE TITLE
Command does not log anything related with oauth with arg `--dump-single-json`

### ISSUE THREAD

**Issue by wisetc** [coletdjnz/yt-dlp-youtube-oauth2#9]
So code like `xxx-xxx-xxx` for google device is not seen.

How do I resolve it?

**Comment by coletdjnz** [comment]
You will need to run yt-dlp once without that option. Once you've given access to yt-dlp it should work.

**Comment by wisetc** [comment]
> You will need to run yt-dlp once without that option. Once you've given access to yt-dlp it should work.

Thank you for your quick answer.

I do it the same way as your suggestion, and it worked. But I think it may be a little bit troublesome. So I doubt there are some simplified ways.

thank you.

**Comment by coletdjnz** [comment]
Yeah it's not the most intuitive. If/when we consider implementing it in yt-dlp officially it may be something we can look at improving if feasible.
